### ISSUE TITLE
Require very large mem and raise Memory Error while generating matrix P

### ISSUE THREAD

**Issue by iFe1er** [jin530/SWalk#3]
Traceback (most recent call last):
  File "run_config.py", line 57, in main
    run_file(c)
  File "run_config.py", line 117, in run_file
    run_single(conf)
  File "run_config.py", line 222, in run_single
    eval_algorithm(train, test, k, a, evaluation, metrics, results, conf, slice=slice, iteration=slice)
  File "run_config.py", line 581, in eval_algorithm
    algorithm.fit(train, test)
  File "/data/services/mining/competition/session_rec/SWalk/algorithms/swalk/swalk.py", line 232, in fit
    model1 = make_SLIST(model=self.model1)
  File "/data/services/mining/competition/session_rec/SWalk/algorithms/swalk/swalk.py", line 145, in make_SLIST
    P = np.linalg.inv(G + np.identity(self.n_items, dtype=np.float16) * self.reg)
  File "<__array_function__ internals>", line 6, in inv
  File "/data/services/anaconda3/envs/franky_tf2/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 545, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 129. GiB for an array with shape (131342, 131342) and data type float64

**Comment by jin530** [comment]
Hello,

As you mentioned, it needs large memory when the number of items is much high since the complexity is proportional to the number of items, not the number of users. 

Thank you for your interest!

**Comment by iFe1er** [comment]
> Hello,
> 
> As you mentioned, it needs large memory when the number of items is much high since the complexity is proportional to the number of items, not the number of users.
> 
> Thank you for your interest!

Thank you for the reply! You are right about the number of items is to many.
Now i now how to solve it, i should reduce number filter ITEMS in every session that appear very rare
